LOCAL_PATH := $(call my-dir)

ifeq ($(CONFIG_USE_INTEL_CERT_PROFILE_SUBSYS), true)

ifneq ($(BOARD_USES_WCS),true)

include $(CLEAR_VARS)
LOCAL_MODULE := Bluetooth
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

endif # BOARD_USES_WCS != true

endif

